# This is a basic workflow to help you get started with Actions

name: CI-delete

# Controls when the action will run.
on:
  # Triggers the workflow on push events for every branch
  delete:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  delete:
    if: github.event.ref_type == 'branch'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true
          tag_name: 'auto-release-${{ github.event.ref }}'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
